version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/benchmark"
    schedule:
      interval: "daily"
