# Typo check: https://github.com/crate-ci/typos

[files]
extend-exclude = ["*.txt"]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
ture = "ture"
hashs = "hashs"
flate = "flate"
TestJSONSlicedInterfaceMixedConvertable = "TestJSONSlicedInterfaceMixedConvertable"

