package clickhouse

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExtractNormalizedInsertQueryAndColumns(t *testing.T) {
	var testCases = []struct {
		name                    string
		query                   string
		expectedNormalizedQuery string
		expectedTableName       string
		expectedColumns         []string
		expectedError           bool
	}{
		{
			name:                    "Regular insert",
			query:                   "INSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Lowercase insert",
			query:                   "insert into table_name (col1, col2) values (1, 2)",
			expectedNormalizedQuery: "insert into table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name: "Insert with mixed case, multiline and format specified",
			query: `INSERT INTO "db"."table_name" (
						col1,
						col2
					) Values (
						1,
						2
					)
					format JSONEachRow`,
			expectedNormalizedQuery: `INSERT INTO "db"."table_name" (
						col1,
						col2
					) FORMAT Native`,
			expectedTableName: "\"db\".\"table_name\"",
			expectedColumns:   []string{"col1", "col2"},
			expectedError:     false,
		},
		{
			name: "Multiline insert",
			query: `INSERT INTO table_name (
						col1,
						col2
					) VALUES (
						1,
						2
					)`,
			expectedNormalizedQuery: `INSERT INTO table_name (
						col1,
						col2
					) FORMAT Native`,
			expectedTableName: "table_name",
			expectedColumns:   []string{"col1", "col2"},
			expectedError:     false,
		},
		{
			name: "Multiline insert, with columns inline",
			query: `INSERT INTO table_name (col1, col2) VALUES (
						1,
						2
					)`,
			expectedNormalizedQuery: `INSERT INTO table_name (col1, col2) FORMAT Native`,
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name: "Multiline insert, with values inline",
			query: `INSERT INTO table_name (
						col1,
						col2
					) VALUES (1, 2)`,
			expectedNormalizedQuery: `INSERT INTO table_name (
						col1,
						col2
					) FORMAT Native`,
			expectedTableName: "table_name",
			expectedColumns:   []string{"col1", "col2"},
			expectedError:     false,
		},
		{
			name:                    "Insert with backtick quoted database and table names",
			query:                   "INSERT INTO `db`.`table_name` (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO `db`.`table_name` (col1, col2) FORMAT Native",
			expectedTableName:       "`db`.`table_name`",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with double quoted database and table names",
			query:                   "INSERT INTO \"db\".\"table_name\" (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO \"db\".\"table_name\" (col1, col2) FORMAT Native",
			expectedTableName:       "\"db\".\"table_name\"",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with special characters in database and table names",
			query:                   "INSERT INTO `_test_1345# $.ДБ`.`2. Таблица №2`",
			expectedNormalizedQuery: "INSERT INTO `_test_1345# $.ДБ`.`2. Таблица №2` FORMAT Native",
			expectedTableName:       "`_test_1345# $.ДБ`.`2. Таблица №2`",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with special characters in database and table names, with columns",
			query:                   "INSERT INTO `_test_1345# $.ДБ`.`2. Таблица №2` (col1, col2)",
			expectedNormalizedQuery: "INSERT INTO `_test_1345# $.ДБ`.`2. Таблица №2` (col1, col2) FORMAT Native",
			expectedTableName:       "`_test_1345# $.ДБ`.`2. Таблица №2`",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with special characters in database and table names, with columns and values",
			query:                   "INSERT INTO `_test_1345# $.ДБ`.`2. Таблица №2` (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO `_test_1345# $.ДБ`.`2. Таблица №2` (col1, col2) FORMAT Native",
			expectedTableName:       "`_test_1345# $.ДБ`.`2. Таблица №2`",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert without database name",
			query:                   "INSERT INTO table_name (col1, col2) VALUES (1, 2) FORMAT Native",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert without columns and values",
			query:                   "INSERT INTO table_name",
			expectedNormalizedQuery: "INSERT INTO table_name FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with format",
			query:                   "INSERT INTO table_name FORMAT Native",
			expectedNormalizedQuery: "INSERT INTO table_name FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with lowercase format",
			query:                   "INSERT INTO table_name format Native",
			expectedNormalizedQuery: "INSERT INTO table_name FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with JSONEachRow format",
			query:                   "INSERT INTO table_name FORMAT JSONEachRow",
			expectedNormalizedQuery: "INSERT INTO table_name FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with quoted table name only",
			query:                   "INSERT INTO `table_name` VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO `table_name` FORMAT Native",
			expectedTableName:       "`table_name`",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:          "Select, should produce error",
			query:         "SELECT * FROM table_name",
			expectedError: true,
		},
		{
			name:                    "Insert with backtick quoted table name and nested columns",
			query:                   "INSERT INTO `table_name` (`col1`.`nested1`, `col1`.`nested2`) VALUES ((1, 2), (1, 2))",
			expectedNormalizedQuery: "INSERT INTO `table_name` (`col1`.`nested1`, `col1`.`nested2`) FORMAT Native",
			expectedTableName:       "`table_name`",
			expectedColumns:         []string{"col1.nested1", "col1.nested2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with single line comment",
			query:                   "-- comment\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with multiple line comments",
			query:                   "-- comment 1\n-- comment 2\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name: "Insert with comment and multiline query",
			query: `-- This is a batch insert
INSERT INTO table_name (
	col1,
	col2
) VALUES (1, 2)`,
			expectedNormalizedQuery: `INSERT INTO table_name (
	col1,
	col2
) FORMAT Native`,
			expectedTableName: "table_name",
			expectedColumns:   []string{"col1", "col2"},
			expectedError:     false,
		},
		{
			name: "Insert with multiple comments and multiline query",
			query: `-- Comment about the table
-- Another comment
INSERT INTO "db"."table_name" (
	col1,
	col2
) VALUES (1, 2)`,
			expectedNormalizedQuery: `INSERT INTO "db"."table_name" (
	col1,
	col2
) FORMAT Native`,
			expectedTableName: "\"db\".\"table_name\"",
			expectedColumns:   []string{"col1", "col2"},
			expectedError:     false,
		},
		{
			name:                    "Insert with comment containing special characters",
			query:                   "-- комментарий на русском языке\nINSERT INTO table_name (col1, col2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with comment and FORMAT",
			query:                   "-- batch insert\nINSERT INTO table_name FORMAT JSONEachRow",
			expectedNormalizedQuery: "INSERT INTO table_name FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name: "Insert with comment and extra whitespace",
			query: `-- comment
    
INSERT INTO table_name (col1, col2)`,
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name: "Insert with comment and backtick quoted names",
			query: `-- Insert into special table
INSERT INTO ` + "`_test_1345# $.ДБ`.`2. Таблица №2`" + ` (col1, col2)`,
			expectedNormalizedQuery: "INSERT INTO `_test_1345# $.ДБ`.`2. Таблица №2` (col1, col2) FORMAT Native",
			expectedTableName:       "`_test_1345# $.ДБ`.`2. Таблица №2`",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with #! comment",
			query:                   "#! comment\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with #! comment without space",
			query:                   "#!comment\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with multiple #! comments",
			query:                   "#! comment 1\n#! comment 2\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with # comment (with space)",
			query:                   "# comment\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with multiple # comments",
			query:                   "# comment 1\n# comment 2\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with mixed comment styles",
			query:                   "-- comment 1\n#! comment 2\n# comment 3\nINSERT INTO table_name (col1, col2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with -- comment after column list",
			query:                   "INSERT INTO table_name (col1, col2) -- columns comment\nVALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with #! comment after column list",
			query:                   "INSERT INTO table_name (col1, col2) #! columns comment\nVALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with # comment after column list",
			query:                   "INSERT INTO table_name (col1, col2) # columns comment\nVALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with -- comment after VALUES",
			query:                   "INSERT INTO table_name (col1, col2) VALUES (1, 2) -- end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with #! comment after VALUES",
			query:                   "INSERT INTO table_name (col1, col2) VALUES (1, 2) #! end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with # comment after VALUES",
			query:                   "INSERT INTO table_name (col1, col2) VALUES (1, 2) # end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with -- comment after column list (no VALUES)",
			query:                   "INSERT INTO table_name (col1, col2) -- end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with #! comment after column list (no VALUES)",
			query:                   "INSERT INTO table_name (col1, col2) #! end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with # comment after column list (no VALUES)",
			query:                   "INSERT INTO table_name (col1, col2) # end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS after column list",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS after column list and trailing VALUES keyword",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 VALUES",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with multiple SETTINGS after column list and VALUES tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1, wait_for_async_insert=0 VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1, wait_for_async_insert=0 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and no column list",
			query:                   "INSERT INTO table_name SETTINGS async_insert=1",
			expectedNormalizedQuery: "INSERT INTO table_name SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with lowercase settings keyword after column list",
			query:                   "INSERT INTO table_name (col1, col2) settings async_insert=1 VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) settings async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS after column list and explicit FORMAT",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT JSONEachRow",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with column named settings is not treated as a SETTINGS clause",
			query:                   "INSERT INTO table_name (col1, settings) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, settings) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "settings"},
			expectedError:           false,
		},
		{
			name:                    "Insert into table named settings is not treated as a SETTINGS clause",
			query:                   "INSERT INTO settings (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO settings (col1, col2) FORMAT Native",
			expectedTableName:       "settings",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name: "Insert with multiline column list ending in a column named settings",
			query: `INSERT INTO table_name (
						col1,
						settings
					) VALUES (1, 2)`,
			expectedNormalizedQuery: `INSERT INTO table_name (
						col1,
						settings
					) FORMAT Native`,
			expectedTableName: "table_name",
			expectedColumns:   []string{"col1", "settings"},
			expectedError:     false,
		},
		{
			name:                    "Insert with SETTINGS after column list and trailing semicolon",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1;",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS after column list and repeated trailing semicolons",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1;;",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and no column list and trailing semicolon",
			query:                   "INSERT INTO table_name SETTINGS async_insert=1;",
			expectedNormalizedQuery: "INSERT INTO table_name SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, trailing VALUES keyword and semicolon",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 VALUES;",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with no SETTINGS and trailing semicolon is unchanged",
			query:                   "INSERT INTO table_name (col1, col2);",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS after column list and trailing -- comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 -- end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS after column list and trailing #! comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 #! end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS after column list and trailing # comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 # end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and no column list and trailing comment",
			query:                   "INSERT INTO table_name SETTINGS async_insert=1 -- end comment",
			expectedNormalizedQuery: "INSERT INTO table_name SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, trailing comment and VALUES keyword on the next line",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 -- end comment\nVALUES",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, trailing VALUES keyword, semicolon and comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 VALUES; -- end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS spread over multiple lines",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1,\n\twait_for_async_insert=0",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1,\n\twait_for_async_insert=0 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS spread over multiple lines and trailing VALUES tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1,\n\twait_for_async_insert=0 VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1,\n\twait_for_async_insert=0 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS spread over multiple lines and an interleaved comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1, -- first setting\n\twait_for_async_insert=0",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1, \n\twait_for_async_insert=0 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a comment marker inside a quoted setting value",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a -- b # c'",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a -- b # c' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with an escaped quote inside a setting value followed by a comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a\\'b' -- end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a\\'b' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a leading comment mentioning a settings assignment",
			query:                   "-- SETTINGS max_threads=1 was removed\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a leading # comment mentioning a settings assignment",
			query:                   "# SETTINGS max_threads=1 was removed\nINSERT INTO table_name (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a leading comment mentioning a settings assignment and a real SETTINGS clause",
			query:                   "-- SETTINGS max_threads=1 was removed\nINSERT INTO table_name (col1, col2) SETTINGS async_insert=1",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and a trailing hash",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 #",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and a trailing block comment containing a line comment marker",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 /* note -- detail */",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and an unterminated trailing block comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 /* note",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a block comment marker inside a quoted setting value",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a /* b */ c'",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a /* b */ c' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with an escaped quote inside a double quoted setting value followed by a comment",
			query:                   `INSERT INTO table_name (col1, col2) SETTINGS log_comment="a\" -- b" -- end comment`,
			expectedNormalizedQuery: `INSERT INTO table_name (col1, col2) SETTINGS log_comment="a\" -- b" FORMAT Native`,
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a doubled quote inside a setting value followed by a comment",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a''b -- c' -- end comment",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a''b -- c' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a VALUES keyword inside a quoted setting value",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a VALUES'",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a VALUES' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and lowercase values tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 values (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and mixed case Values tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 Values (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, VALUES tuples and a trailing newline",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 VALUES (1, 2)\n",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and VALUES tuples without a separating space",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 VALUES(1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and VALUES tuples spanning multiple lines",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 VALUES (\n\t1,\n\t2\n)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS and VALUES tuples holding a comment marker",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 values (1, 'a -- b')",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, no column list and lowercase values tuples",
			query:                   "INSERT INTO table_name SETTINGS async_insert=1 values (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with a setting value ending in values",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment=my_values",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment=my_values FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a setting name starting with values",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS values_of_test=1",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS values_of_test=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, a block comment and VALUES tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 /* end comment */VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, a block comment and a trailing VALUES keyword",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 /* end comment */VALUES",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with SETTINGS, a semicolon and VALUES tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1;VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a commented out SETTINGS clause after the column list",
			query:                   "INSERT INTO table_name (col1, col2) -- SETTINGS async_insert=1",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a SETTINGS clause inside a trailing block comment",
			query:                   "INSERT INTO table_name (col1, col2) /* SETTINGS async_insert=1 */",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a SETTINGS clause inside a leading block comment",
			query:                   "/* SETTINGS async_insert=1 */\nINSERT INTO table_name (col1, col2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a leading block comment and a real SETTINGS clause",
			query:                   "/* note */ INSERT INTO table_name (col1, col2) SETTINGS async_insert=1",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a block comment between the column list and the SETTINGS clause",
			query:                   "INSERT INTO table_name (col1, col2)/* note */SETTINGS async_insert=1",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a comment inside the column list",
			query:                   "INSERT INTO table_name (col1, /* note */ col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1,  col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a VALUES keyword surrounded by whitespace inside a quoted setting value",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a VALUES b'",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a VALUES b' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a FORMAT clause inside a quoted setting value",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='see FORMAT Native'",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='see FORMAT Native' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a quoted setting value holding a VALUES keyword and real VALUES tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a VALUES b' VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a VALUES b' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert into a table named values",
			query:                   "INSERT INTO values (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO values (col1, col2) FORMAT Native",
			expectedTableName:       "values",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a column named values",
			query:                   "INSERT INTO table_name (col1, values) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, values) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "values"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a column named format",
			query:                   "INSERT INTO table_name (col1, format) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, format) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "format"},
			expectedError:           false,
		},
		{
			name:                    "Insert into a table named format",
			query:                   "INSERT INTO format (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO format (col1, col2) FORMAT Native",
			expectedTableName:       "format",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a heredoc setting value holding a quote and VALUES tuples",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment=$$don't VALUES$$ VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment=$$don't VALUES$$ FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a tagged heredoc setting value holding a comment marker",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment=$tag$a -- b$tag$",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment=$tag$a -- b$tag$ FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert without column list ended by a statement terminator",
			query:                   "INSERT INTO table_name;",
			expectedNormalizedQuery: "INSERT INTO table_name FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert without column list with a format ended by a statement terminator",
			query:                   "INSERT INTO table_name FORMAT Native;",
			expectedNormalizedQuery: "INSERT INTO table_name FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{},
			expectedError:           false,
		},
		{
			name:                    "Insert with a format ended by a statement terminator",
			query:                   "INSERT INTO table_name (col1, col2) FORMAT JSONEachRow;",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a settings clause not separated from the column list",
			query:                   "INSERT INTO table_name (col1, col2)SETTINGS async_insert=1",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS async_insert=1 FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with row data not separated from the column list",
			query:                   "INSERT INTO table_name (col1, col2)VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a format not separated from the column list",
			query:                   "INSERT INTO table_name (col1, col2)FORMAT JSONEachRow",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a statement terminator inside a quoted setting value",
			query:                   "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a;b';",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) SETTINGS log_comment='a;b' FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a settings assignment inside row data not separated from the column list",
			query:                   "INSERT INTO table_name (col1, col2)VALUES (1, 'a SETTINGS async_insert=1')",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert with a settings assignment inside row data written after a format",
			query:                   "INSERT INTO table_name (col1, col2) FORMAT CSV\n1,'a SETTINGS async_insert=1'",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, col2) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
		{
			name:                    "Insert into a column whose quoted name holds a settings assignment",
			query:                   "INSERT INTO table_name (col1, `SETTINGS async_insert=1`) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO table_name (col1, `SETTINGS async_insert=1`) FORMAT Native",
			expectedTableName:       "table_name",
			expectedColumns:         []string{"col1", "SETTINGS async_insert=1"},
			expectedError:           false,
		},
		{
			name:                    "Insert into a table whose name ends with the settings keyword",
			query:                   "INSERT INTO mysettings (col1, col2) VALUES (1, 2)",
			expectedNormalizedQuery: "INSERT INTO mysettings (col1, col2) FORMAT Native",
			expectedTableName:       "mysettings",
			expectedColumns:         []string{"col1", "col2"},
			expectedError:           false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.query, func(t *testing.T) {
			normalizedQuery, tableName, columns, err := extractNormalizedInsertQueryAndColumns(tc.query)
			if tc.expectedError {
				assert.Error(t, err)
				return
			}

			assert.NoError(t, err)
			assert.Equal(t, tc.expectedNormalizedQuery, normalizedQuery)
			assert.Equal(t, tc.expectedTableName, tableName)
			assert.Equal(t, tc.expectedColumns, columns)
		})
	}
}
