
// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/array.tpl

package column

import (
	"database/sql"
    "database/sql/driver"
	"github.com/ClickHouse/ch-go/proto"
	"github.com/google/uuid"
	"github.com/paulmach/orb"
	"github.com/shopspring/decimal"
	"math/big"
	"net"
	"net/netip"
	"time"
	"fmt"
)

// appendRowPlain is a reflection-free realisation of append for plain arrays.
func (col *Array) appendRowPlain(v any) error {
	switch tv := v.(type) {
	{{- range . }}
	case []{{ . }}:
		return appendRowPlain(col, tv)
	case []*{{ . }}:
		return appendNullableRowPlain(col, tv)
	{{- end }}
	default:
	    if valuer, ok := v.(driver.Valuer); ok {
            val, err := valuer.Value()
            if err != nil {
                return &ColumnConverterError{
                    Op:   "AppendRow",
                    To:   "Array",
                    From: fmt.Sprintf("%T", v),
                    Hint: "could not get driver.Valuer value",
                }
            }
            return col.appendRowPlain(val)
        }
		return col.appendRowDefault(v)
	}
}

// appendBulkPlain dispatches typed [][]T inputs (one slice per row of a depth-1
// Array column) through the inner column's typed Append fast path, avoiding
// the reflection loop in Array.Append. Returns (true, err) when a typed case
// matched, (false, nil) to signal the caller should fall through to reflection.
func (col *Array) appendBulkPlain(v any) (bool, error) {
	switch tv := v.(type) {
	{{- range . }}
	case [][]{{ . }}:
		return true, appendBulkPlain(col, tv)
	case [][]*{{ . }}:
		return true, appendNullableBulkPlain(col, tv)
	{{- end }}
	default:
		return false, nil
	}
}
