// +build amd64 arm64

// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/column_safe.tpl

package column

import (
	"unsafe"
	"reflect"
	"github.com/ClickHouse/clickhouse-go/v2/lib/binary"
)


{{- range . }}

func (col *{{ .ChType }}) Decode(decoder *binary.Decoder, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = {{ .Size }} / 8

	*col = append(*col, make([]{{ .GoType }}, rows)...)

	var dst []byte
	slice := (*reflect.SliceHeader)(unsafe.Pointer(&dst))
	slice.Data = (*reflect.SliceHeader)(unsafe.Pointer(col)).Data
	slice.Len = len(*col) * size
	slice.Cap = cap(*col) * size

	if err := decoder.Raw(dst); err != nil {
		return err
	}
	return nil
}

func (col *{{ .ChType }}) Encode(encoder *binary.Encoder) error {
	if len(*col) == 0 {
		return nil
	}
	const size = {{ .Size }} / 8
	scratch := make([]byte, size*len(*col))
	{
	    var src []byte
	    slice := (*reflect.SliceHeader)(unsafe.Pointer(&src))
	    slice.Data = (*reflect.SliceHeader)(unsafe.Pointer(col)).Data
	    slice.Len = len(*col) * size
        slice.Cap = cap(*col) * size

		copy(scratch, src)
	}
	return encoder.Raw(scratch)
}

{{- end }}
